# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: processor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import message_pb2 as message__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='processor.proto',
  package='processor',
  syntax='proto3',
  serialized_pb=_b('\n\x0fprocessor.proto\x12\tprocessor\x1a\rmessage.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x19\n\x06Status\x12\x0f\n\x07message\x18\x01 \x01(\t2q\n\tProcessor\x12\x33\n\x04Ping\x12\x16.google.protobuf.Empty\x1a\x11.processor.Status\"\x00\x12/\n\x07Process\x12\x10.message.Message\x1a\x10.message.Message\"\x00\x42H\n3org.springframework.cloud.stream.app.grpc.processorB\x0fProcessorProtosP\x01\x62\x06proto3')
  ,
  dependencies=[message__pb2.DESCRIPTOR,google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_STATUS = _descriptor.Descriptor(
  name='Status',
  full_name='processor.Status',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='processor.Status.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=99,
)

DESCRIPTOR.message_types_by_name['Status'] = _STATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Status = _reflection.GeneratedProtocolMessageType('Status', (_message.Message,), dict(
  DESCRIPTOR = _STATUS,
  __module__ = 'processor_pb2'
  # @@protoc_insertion_point(class_scope:processor.Status)
  ))
_sym_db.RegisterMessage(Status)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n3org.springframework.cloud.stream.app.grpc.processorB\017ProcessorProtosP\001'))
# @@protoc_insertion_point(module_scope)
